-- MySQL Script generated by MySQL Workbench
-- 12/07/15 20:30:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `role_name` VARCHAR(30) NOT NULL COMMENT '',
  PRIMARY KEY (`role_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`school` (
  `school_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `school_name` VARCHAR(100) NOT NULL COMMENT '',
  `address` VARCHAR(225) NULL COMMENT '',
  PRIMARY KEY (`school_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `name` VARCHAR(80) NOT NULL COMMENT '',
  `username` VARCHAR(80) NOT NULL COMMENT '',
  `pass` VARCHAR(32) NOT NULL COMMENT '',
  `email` VARCHAR(80) NOT NULL COMMENT '',
  `no_telp` VARCHAR(20) NOT NULL COMMENT '',
  `role_id` INT(11) NOT NULL COMMENT '',
  `uri` VARCHAR(80) NOT NULL COMMENT '',
  `pict` VARCHAR(80) NOT NULL DEFAULT 'assets/images/users/default.jpg 	' COMMENT '',
  `bio` TEXT NOT NULL COMMENT '',
  `status` VARCHAR(15) NOT NULL COMMENT '',
  `school_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  UNIQUE INDEX `username` (`username` ASC)  COMMENT '',
  INDEX `role_id` (`role_id` ASC)  COMMENT '',
  INDEX `fk_users_school1_idx` (`school_id` ASC)  COMMENT '',
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_school1`
    FOREIGN KEY (`school_id`)
    REFERENCES `mydb`.`school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`nodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nodes` (
  `node_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  `module` VARCHAR(30) NOT NULL COMMENT '',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `modified` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `uri` VARCHAR(80) NOT NULL COMMENT '',
  `title` VARCHAR(80) NOT NULL COMMENT '',
  `content` TEXT NOT NULL COMMENT '',
  `note` VARCHAR(225) NOT NULL COMMENT '',
  `status` VARCHAR(30) NOT NULL COMMENT '',
  PRIMARY KEY (`node_id`)  COMMENT '',
  INDEX `user_id` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `nodes_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`menus` (
  `menu_id` INT(11) NOT NULL COMMENT '',
  `role_id` VARCHAR(11) NOT NULL COMMENT '',
  `position` VARCHAR(15) NOT NULL COMMENT '',
  `module_target` VARCHAR(30) NOT NULL COMMENT '',
  PRIMARY KEY (`position`, `module_target`)  COMMENT '',
  INDEX `node_id` (`role_id` ASC)  COMMENT '',
  INDEX `role_id` (`role_id` ASC)  COMMENT '',
  INDEX `node_id_2` (`menu_id` ASC)  COMMENT '',
  INDEX `role_id_2` (`role_id` ASC)  COMMENT '',
  CONSTRAINT `menus_ibfk_5`
    FOREIGN KEY (`menu_id`)
    REFERENCES `mydb`.`nodes` (`node_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`role_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role_permissions` (
  `permission_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `role_id` INT(11) NOT NULL COMMENT '',
  `module` VARCHAR(30) NOT NULL COMMENT '',
  `permission` VARCHAR(80) NOT NULL COMMENT '',
  PRIMARY KEY (`role_id`, `module`, `permission`)  COMMENT '',
  UNIQUE INDEX `permission_id` (`permission_id` ASC)  COMMENT '',
  CONSTRAINT `role_permissions_ibfk_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`roles` (`role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`sites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sites` (
  `primary` INT(11) NOT NULL DEFAULT '1' COMMENT '',
  `site_name` VARCHAR(225) NOT NULL COMMENT '',
  `site_title` VARCHAR(225) NOT NULL COMMENT '',
  `site_url` VARCHAR(225) NOT NULL COMMENT '',
  `site_logo` VARCHAR(255) NOT NULL COMMENT '',
  `date_format` VARCHAR(20) NOT NULL COMMENT '',
  `rows_per_page` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`primary`)  COMMENT '',
  INDEX `primary_2` (`primary` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`level` (
  `level_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `level` VARCHAR(45) NOT NULL COMMENT '',
  `umur_bawah` INT NOT NULL COMMENT '',
  `umur_atas` INT NOT NULL COMMENT '',
  PRIMARY KEY (`level_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `category` VARCHAR(45) NOT NULL COMMENT '',
  `description` TEXT NOT NULL COMMENT '',
  `strong` TEXT NULL COMMENT '',
  `weak` TEXT NULL COMMENT '',
  PRIMARY KEY (`category_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video` (
  `video_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `category_id` INT NOT NULL COMMENT '',
  `level_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`video_id`)  COMMENT '',
  INDEX `fk_video_Kategori1_idx` (`category_id` ASC)  COMMENT '',
  INDEX `fk_video_level1_idx` (`level_id` ASC)  COMMENT '',
  CONSTRAINT `fk_video_Kategori1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_nodes1`
    FOREIGN KEY (`video_id`)
    REFERENCES `mydb`.`nodes` (`node_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_level1`
    FOREIGN KEY (`level_id`)
    REFERENCES `mydb`.`level` (`level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `question_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `category_id` INT NOT NULL COMMENT '',
  `point` INT NOT NULL COMMENT '',
  `question_type` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`question_id`)  COMMENT '',
  INDEX `fk_pertanyaan_category1_idx` (`category_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pertanyaan_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_nodes1`
    FOREIGN KEY (`question_id`)
    REFERENCES `mydb`.`nodes` (`node_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`test` (
  `test_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `video_video_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`test_id`)  COMMENT '',
  INDEX `fk_test_video1_idx` (`video_video_id` ASC)  COMMENT '',
  CONSTRAINT `fk_test_video1`
    FOREIGN KEY (`video_video_id`)
    REFERENCES `mydb`.`video` (`video_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`test_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`test_question` (
  `test_id` INT NOT NULL COMMENT '',
  `question_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`test_id`, `question_id`)  COMMENT '',
  INDEX `fk_test_question_question1_idx` (`question_id` ASC)  COMMENT '',
  CONSTRAINT `fk_test_question_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `mydb`.`test` (`test_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_question_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `mydb`.`question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`watched_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`watched_video` (
  `user_id` INT NOT NULL COMMENT '',
  `video_id` INT NOT NULL COMMENT '',
  `date` INT NOT NULL COMMENT '',
  `score` INT NULL COMMENT '',
  `time` INT NULL COMMENT '',
  INDEX `fk_watched_video_users1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_watched_video_video1_idx` (`video_id` ASC)  COMMENT '',
  CONSTRAINT `fk_watched_video_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_watched_video_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `mydb`.`video` (`video_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`test_taker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`test_taker` (
  `test_id` INT NOT NULL COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  `test_taker_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` INT NOT NULL COMMENT '',
  INDEX `fk_test_taker_test1_idx` (`test_id` ASC)  COMMENT '',
  INDEX `fk_test_taker_users1_idx` (`user_id` ASC)  COMMENT '',
  PRIMARY KEY (`test_taker_id`)  COMMENT '',
  CONSTRAINT `fk_test_taker_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `mydb`.`test` (`test_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_taker_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`test_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`test_answer` (
  `test_taker_id` INT NOT NULL COMMENT '',
  `question_id` INT NOT NULL COMMENT '',
  `test_answer` VARCHAR(45) NULL COMMENT '',
  `date` INT NULL COMMENT '',
  `time_taken` INT NULL COMMENT '',
  `score` INT NULL COMMENT '',
  `status` VARCHAR(20) NULL COMMENT '',
  PRIMARY KEY (`question_id`, `test_taker_id`)  COMMENT '',
  INDEX `fk_test_answer_question1_idx` (`question_id` ASC)  COMMENT '',
  CONSTRAINT `fk_test_answer_test_taker1`
    FOREIGN KEY (`test_taker_id`)
    REFERENCES `mydb`.`test_taker` (`test_taker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_answer_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `mydb`.`question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prelevel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prelevel` (
  `level_id` INT NOT NULL COMMENT '',
  `prelevel` INT NOT NULL COMMENT '',
  PRIMARY KEY (`level_id`, `prelevel`)  COMMENT '',
  INDEX `fk_prelevel_level2_idx` (`prelevel` ASC)  COMMENT '',
  CONSTRAINT `fk_prelevel_level1`
    FOREIGN KEY (`level_id`)
    REFERENCES `mydb`.`level` (`level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prelevel_level2`
    FOREIGN KEY (`prelevel`)
    REFERENCES `mydb`.`level` (`level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
